/** 
 * O comando abaixo remove todas as tabelas, isso possibilita testar
 * a criação do banco, várias vezes se necessário.
 */
DROP TABLE IF EXISTS CLIENTE, LIVRO, AUTOR, AUTORLIVRO , VENDAS 
CASCADE;

CREATE TABLE CLIENTE (

   IDCLIENTE   INT,

   NOME CHAR(30),

   ENDERECO VARCHAR(50),

   PRIMARY KEY (IDCLIENTE)

);

CREATE TABLE LIVRO (

   CODLIVRO INT,

   TITULO CHAR(20),

   ANO INT,

   EDITORA CHAR(20),

   AREA CHAR(15),

   PRECO NUMERIC (5,2),

   PRIMARY KEY (CODLIVRO)

);

 CREATE TABLE AUTOR (

   CODAUTOR INT,

   NOME CHAR(20),

   PRIMARY KEY (CODAUTOR)

);

CREATE TABLE AUTORLIVRO (

   CODAUTOR INT,

   CODLIVRO INT,

   PRIMARY KEY (CODAUTOR, CODLIVRO),

   FOREIGN KEY (CODAUTOR) REFERENCES AUTOR (CODAUTOR),

   FOREIGN KEY (CODLIVRO) REFERENCES LIVRO (CODLIVRO)

);

-- Tabela de vendas
drop table if exists VENDA;
CREATE TABLE VENDA(
	CODVENDA INT, 
	CODCLIENTE INT, 
	CODLIVRO INT, 
	DATAVENDA CHAR(10), 
	QUANTIDADE INT, 
	VALORPAGO NUMERIC(9,2),
	
	PRIMARY KEY (CODVENDA),
	
	FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE (IDCLIENTE),
	FOREIGN KEY (CODLIVRO) REFERENCES LIVRO (CODLIVRO)
);

